from __future__ import annotations
from typing import Protocol, Sequence
from uuid import UUID
from omega.config import Capability
from omega.domain import WorkflowRun

class ModelGateway(Protocol):
    name: str
    capabilities: frozenset[Capability]
    priority: int
    async def complete(self, *, system: str, prompt: str) -> str: ...
    async def healthy(self) -> bool: ...

class RunRepository(Protocol):
    async def add(self, run: WorkflowRun) -> None: ...
    async def get(self, tenant_id: UUID, run_id: UUID) -> WorkflowRun | None: ...
    async def save(self, tenant_id: UUID, run: WorkflowRun) -> None: ...
    async def append_event(self, tenant_id: UUID, run_id: UUID, kind: str, payload: dict[str, object]) -> None: ...

class ModelRegistry(Protocol):
    def all(self) -> Sequence[ModelGateway]: ...
